// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:push_app/config/environment/environment.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Environment.androidFirebaseKey,
    appId: '1:217575096875:android:6f33e857f7ef50d923206e',
    messagingSenderId: '217575096875',
    projectId: 'firechat-d3ffd',
    databaseURL: 'https://firechat-d3ffd.firebaseio.com',
    storageBucket: 'firechat-d3ffd.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Environment.iosFirebaseKey,
    appId: '1:217575096875:ios:204f64cb3881e9f623206e',
    messagingSenderId: '217575096875',
    projectId: 'firechat-d3ffd',
    databaseURL: 'https://firechat-d3ffd.firebaseio.com',
    storageBucket: 'firechat-d3ffd.appspot.com',
    iosClientId:
        '217575096875-7iekl19l5p5hkkcjkju1n1idq1urjuqb.apps.googleusercontent.com',
    iosBundleId: 'com.ariz.pushApp',
  );
}
